export const EN = {
  "common.settings": "Settings",
  "common.back": "Back",
  "common.close": "Close",
  "common.save": "Save",
  "common.discard": "Discard",
  "common.delete": "Delete",
  "common.add": "Add",
  "common.empty": "empty",
  "common.enabled": "Enabled",
  "common.disabled": "Disabled",
  "workspace.resizeFiles": "Resize file panel",
  "workspace.resizeActivity": "Resize activity panel",
  "workspace.activity": "Activity",
  "workspace.pending": "Pending",
  "workspace.chat": "Chat",
  "library.title": "Audio Files",
  "library.openFolder": "Open folder",
  "library.scanning": "Scanning…",
  "library.itemCount": "{count} items",
  "library.filteredCount": "{count}/{total} items",
  "library.searchLabel": "Search audio files",
  "library.search": "Search",
  "library.unsaved": "Unsaved changes",
  "library.noMatches": "No matching files",
  "tags.title": "Audio tags",
  "tags.noFiles": "No audio files found",
  "tags.original": "Original",
  "tags.modified": "Modified",
  "tags.modifiedField": "Modified {label}",
  "tags.artworkPending": "Generated artwork · pending acceptance",
  "tags.artworkPreview": "Generated artwork preview",
  "tags.artworkStorage": "Stored in .temp until accepted. Existing files are preserved.",
  "tags.addField": "Add field",
  "tags.chooseFolder": "Choose another folder or add supported audio files within 5 folder levels.",
  "tags.previous": "Prev",
  "tags.next": "Next",
  "tags.exportImage": "Export image",
  "tags.importImage": "Import image",
  "tags.revertField": "Revert field",
  "tags.clearImage": "Clear image",
  "tags.clearField": "Clear field",
  "pending.count": "{count} changed",
  "pending.empty": "No pending changes",
  "pending.artwork": "Generated artwork",
  "pending.saving": "Saving {done}/{total}",
  "pending.saveAll": "Accept all",
  "pending.discardAll": "Discard all",
  "settings.audioTags": "Audio Tag",
  "settings.commands": "Commands",
  "settings.language": "Language",
  "settings.autoSave": "Changes apply immediately and are saved automatically.",
  "settings.defaultFields": "Default Fields",
  "settings.defaultFieldsDescription": "Default fields always appear in this order, even when empty. Other fields appear after them only while they have content; clearing an other field removes it on save.",
  "settings.removeDefault": "Remove from defaults",
  "settings.addDefault": "Add default field",
  "settings.commandManagement": "Command management",
  "settings.commandDescription": "Click a command to enable or disable it. Changes are saved automatically.",
  "models.required": "Base URL and Model are required.",
  "models.duplicate": "Model already exists.",
  "models.title": "OpenAI-compatible API",
  "models.description": "Used for conversations and commands. Any OpenAI-compatible endpoint works.",
  "models.new": "New model",
  "models.active": "{model} · Active",
  "models.model": "Model",
  "models.baseUrl": "Base URL",
  "models.apiKey": "API Key",
  "models.uploadAudio": "Upload audio",
  "models.webSearch": "Web search",
  "models.imageGeneration": "Image generation",
  "models.filesPerRequest": "Files per request",
  "models.concurrency": "Concurrency",
  "models.timeout": "Maximum wait (seconds)",
  "models.timeoutDescription": "Timeout per LLM request, 60 seconds by default. Metadata batches are timed separately.",
  "chat.summary": "{count} files · {batchSize}/request · {concurrency} concurrent",
  "chat.conversation": "Conversation",
  "chat.empty": "Chat normally, or send /meta to complete metadata, /organise to organise files, and /image to download artwork.",
  "chat.role.user": "User",
  "chat.role.assistant": "Assistant",
  "chat.role.system": "System",
  "chat.sending": "Sending…",
  "chat.saving": "Saving changes…",
  "chat.pendingWarning": "Save or discard pending changes before running commands. You can still chat.",
  "chat.stop": "Stop",
  "chat.clear": "Clear",
  "chat.message": "Message",
  "chat.placeholder": "Send a message or choose a /command…",
  "chat.addModel": "Add a model in LLM settings",
  "chat.selectModel": "Select model",
  "chat.send": "Send",
  "chat.stopped": "Conversation stopped.",
  "commands.noneAvailable": "None. Enable commands in Settings.",
  "commands.unknown": "Unknown command: {input}. Available commands: {available}",
  "commands.disabled": "{command} is disabled. Enable it in Settings → Commands.",
  "commands.noArguments": "{command} does not accept arguments. Send the command on its own.",
  "commands.pendingChanges": "Save or discard pending changes before running commands.",
  "commands.failed": "{command} failed: {message}",
  "commands.stopped": "{command} stopped.",
  "commands.openAudioFolder": "Open a folder containing audio files first.",
  "commands.openArtworkFolder": "Open the music folder that needs artwork first.",
  "commands.openOrganiseFolder": "Open the music folder to organise first.",
  "commands.meta.description": "Complete missing metadata using the default prompt; review changes before saving.",
  "commands.meta.progress": "Completing audio metadata…",
  "commands.meta.missingJson": "No metadata JSON was returned.",
  "commands.meta.invalidJson": "The model returned invalid metadata JSON. Check the response format required by the prompt.",
  "commands.meta.invalidFormat": "Invalid metadata format.",
  "commands.meta.invalidFile": "Invalid metadata format for {file}.",
  "commands.meta.invalidField": "Invalid {field} for {file}; expected a string.",
  "commands.meta.batchFailed": "Batch {batch} failed: {message}",
  "commands.meta.completed": "Metadata completion finished: {count} files have pending changes. Review before saving.",
  "commands.organise.description": "Organise audio files by artist and title when sent.",
  "commands.organise.progress": "Organising audio files…",
  "commands.image.description": "Download missing artwork for organised artist folders; review and accept embedded cover changes.",
  "commands.image.progress": "Searching for and downloading missing artwork…",
  "commands.imageGeneration.description": "Stage generated artwork in .temp; accept to save artist images and missing audio covers.",
  "commands.imageGeneration.progress": "Generating artist artwork and preparing covers for review…",
  "commands.lyrics.description": "Generate missing LRC lyrics, preserve existing lyrics, and review before saving.",
  "commands.lyrics.progress": "Generating LRC lyrics for tracks with missing lyrics…",
  "commands.lyrics.skipped": "All tracks already have lyrics. Nothing to generate.",
  "fields.image": "Album cover",
  "fields.title": "Title",
  "fields.artist": "Artist",
  "fields.album": "Album",
  "fields.year": "Year",
  "fields.genre": "Genre",
  "fields.bpm": "BPM",
  "fields.comment": "Comment",
  "fields.lyrics": "Lyrics",
  "fields.album_artist": "Album Artist",
  "fields.composer": "Composer",
  "fields.track_number": "Track Number",
  "fields.track_total": "Track Total",
  "fields.disc_number": "Disc Number",
  "fields.disc_total": "Disc Total",
  "fields.subtitle": "Subtitle",
  "fields.description": "Description",
  "fields.grouping": "Grouping",
  "fields.copyright": "Copyright",
  "fields.conductor": "Conductor",
  "fields.remixedby": "Remixed By",
  "fields.publisher": "Publisher",
  "fields.isrc": "ISRC",
  "fields.initial_key": "Initial Key",
  "fields.musicbrainz_artist_id": "MusicBrainz Artist ID",
  "fields.musicbrainz_album_id": "MusicBrainz Album ID",
  "fields.musicbrainz_albumartist_id": "MusicBrainz Album Artist ID",
  "fields.musicbrainz_track_id": "MusicBrainz Track ID",
  "fields.musicbrainz_release_group_id": "MusicBrainz Release Group ID",
  "fields.musicbrainz_disc_id": "MusicBrainz Disc ID",
  "fields.musicbrainz_release_status": "MusicBrainz Release Status",
  "fields.musicbrainz_release_type": "MusicBrainz Release Type",
  "fields.musicbrainz_release_country": "MusicBrainz Release Country",
  "fields.musicip_id": "MusicIP ID",
  "fields.amazon_id": "Amazon ID",
} as const;
