import type { TranslationCatalog } from "./index";

export const ZH_CN = {
  "common.settings": "设置",
  "common.back": "返回",
  "common.close": "关闭",
  "common.save": "保存",
  "common.discard": "放弃",
  "common.delete": "删除",
  "common.add": "添加",
  "common.empty": "空",
  "common.enabled": "已启用",
  "common.disabled": "未启用",
  "workspace.resizeFiles": "调整文件面板宽度",
  "workspace.resizeActivity": "调整活动面板宽度",
  "workspace.activity": "活动",
  "workspace.pending": "待保存",
  "workspace.chat": "对话",
  "library.title": "音频文件",
  "library.openFolder": "打开文件夹",
  "library.scanning": "扫描中…",
  "library.itemCount": "{count} 项",
  "library.filteredCount": "{count}/{total} 项",
  "library.searchLabel": "搜索音频文件",
  "library.search": "搜索",
  "library.unsaved": "未保存修改",
  "library.noMatches": "没有匹配的文件",
  "tags.title": "音频标签",
  "tags.noFiles": "未找到音频文件",
  "tags.original": "原始值",
  "tags.modified": "修改值",
  "tags.modifiedField": "修改值：{label}",
  "tags.artworkPending": "生成图片 · 等待审核",
  "tags.artworkPreview": "生成图片预览",
  "tags.artworkStorage": "暂存于 .temp，确认保存后写入，已有文件保留。",
  "tags.addField": "添加字段",
  "tags.chooseFolder": "请选择其他文件夹，或在 5 层目录范围内添加支持的音频文件。",
  "tags.previous": "上一个",
  "tags.next": "下一个",
  "tags.exportImage": "导出图片",
  "tags.importImage": "导入图片",
  "tags.revertField": "还原字段",
  "tags.clearImage": "清除图片",
  "tags.clearField": "清空字段",
  "pending.count": "{count} 个已修改",
  "pending.empty": "没有待保存的修改",
  "pending.artwork": "生成图片",
  "pending.saving": "保存中 {done}/{total}",
  "pending.saveAll": "全部保存",
  "pending.discardAll": "全部放弃",
  "settings.audioTags": "音频标签",
  "settings.commands": "命令管理",
  "settings.language": "语言",
  "settings.autoSave": "切换后立即生效并自动保存。",
  "settings.defaultFields": "默认字段",
  "settings.defaultFieldsDescription": "默认字段始终按此顺序显示，即使为空。其他字段仅在有内容时显示，清空后将在保存时移除。",
  "settings.removeDefault": "从默认字段移除",
  "settings.addDefault": "添加默认字段",
  "settings.commandManagement": "命令管理",
  "settings.commandDescription": "点击命令启用，再次点击取消启用，修改自动保存。",
  "models.required": "接口地址和模型不能为空。",
  "models.duplicate": "模型已存在，不能重复。",
  "models.title": "兼容 OpenAI 的接口",
  "models.description": "用于对话和命令，支持兼容 OpenAI 的接口。",
  "models.new": "新模型",
  "models.active": "{model} · 当前模型",
  "models.model": "模型",
  "models.baseUrl": "接口地址",
  "models.apiKey": "API 密钥",
  "models.uploadAudio": "音频上传",
  "models.webSearch": "联网搜索",
  "models.imageGeneration": "图片生成",
  "models.filesPerRequest": "每批文件数",
  "models.concurrency": "并发数",
  "models.timeout": "最多等待秒数",
  "models.timeoutDescription": "单次 LLM 请求的等待上限，默认 60 秒；元数据补齐按每批请求计时。",
  "chat.summary": "{count} 个文件 · {batchSize}/批 · {concurrency} 并发",
  "chat.conversation": "对话记录",
  "chat.empty": "可以直接对话，或发送 /meta 补齐元数据、/organise 整理文件、/image 下载图片。",
  "chat.role.user": "用户",
  "chat.role.assistant": "助手",
  "chat.role.system": "系统",
  "chat.sending": "发送中…",
  "chat.saving": "正在保存修改…",
  "chat.pendingWarning": "运行命令前请保存或放弃待确认修改，仍可继续对话。",
  "chat.stop": "停止",
  "chat.clear": "清空",
  "chat.message": "消息",
  "chat.placeholder": "输入消息或选择 /命令…",
  "chat.addModel": "请在 LLM 设置中添加模型",
  "chat.selectModel": "选择模型",
  "chat.send": "发送",
  "chat.stopped": "对话已停止。",
  "commands.noneAvailable": "无，请在设置中启用命令。",
  "commands.unknown": "未知命令：{input}。可用命令：{available}",
  "commands.disabled": "{command} 未启用，请在设置 → 命令管理中启用。",
  "commands.noArguments": "{command} 不接受额外参数，请单独发送该命令。",
  "commands.pendingChanges": "请先保存或放弃待处理修改，再执行命令。",
  "commands.failed": "{command} 执行失败：{message}",
  "commands.stopped": "{command} 已停止。",
  "commands.openAudioFolder": "请先打开包含音频文件的目录。",
  "commands.openArtworkFolder": "请先打开需要补充图片的音乐目录。",
  "commands.openOrganiseFolder": "请先打开需要整理的音乐目录。",
  "commands.meta.description": "使用默认提示词补齐缺失元数据，生成待确认修改；发送后执行。",
  "commands.meta.progress": "正在补齐音频元数据…",
  "commands.meta.missingJson": "未返回元数据 JSON。",
  "commands.meta.invalidJson": "模型返回的元数据不是有效 JSON，请检查提示词要求的返回格式。",
  "commands.meta.invalidFormat": "元数据格式无效。",
  "commands.meta.invalidFile": "{file} 的元数据格式无效。",
  "commands.meta.invalidField": "{file} 的 {field} 格式无效，应为字符串。",
  "commands.meta.batchFailed": "第 {batch} 批失败：{message}",
  "commands.meta.completed": "元数据补齐完成：{count} 个文件产生待确认修改，请检查后保存。",
  "commands.organise.description": "按歌手和歌名重新组织音频文件；发送后执行。",
  "commands.organise.progress": "正在重新组织音频文件…",
  "commands.image.description": "为已整理的歌手目录下载缺失图片；音频封面需人工确认保存。",
  "commands.image.progress": "正在查询并下载缺失图片…",
  "commands.imageGeneration.description": "生成图片暂存于 .temp；确认保存后写入歌手图片和缺失的音频封面。",
  "commands.imageGeneration.progress": "正在生成歌手图片并准备待审核封面…",
  "commands.lyrics.description": "为缺失歌词的音频生成 LRC 歌词，跳过已有歌词，审阅后保存。",
  "commands.lyrics.progress": "正在为缺失歌词的音频生成待审阅 LRC 歌词…",
  "commands.lyrics.skipped": "所有歌曲均已有歌词，已跳过，无需生成。",
  "fields.image": "封面",
  "fields.title": "歌名",
  "fields.artist": "歌手",
  "fields.album": "专辑",
  "fields.year": "年份",
  "fields.genre": "流派",
  "fields.bpm": "节拍",
  "fields.comment": "备注",
  "fields.lyrics": "歌词",
  "fields.album_artist": "专辑歌手",
  "fields.composer": "作曲",
  "fields.track_number": "音轨",
  "fields.track_total": "总音轨数",
  "fields.disc_number": "碟号",
  "fields.disc_total": "总碟数",
  "fields.subtitle": "副标题",
  "fields.description": "描述",
  "fields.grouping": "分组",
  "fields.copyright": "版权",
  "fields.conductor": "指挥",
  "fields.remixedby": "混音者",
  "fields.publisher": "发行方",
  "fields.isrc": "ISRC",
  "fields.initial_key": "初始调性",
  "fields.musicbrainz_artist_id": "MusicBrainz 歌手 ID",
  "fields.musicbrainz_album_id": "MusicBrainz 专辑 ID",
  "fields.musicbrainz_albumartist_id": "MusicBrainz 专辑歌手 ID",
  "fields.musicbrainz_track_id": "MusicBrainz 音轨 ID",
  "fields.musicbrainz_release_group_id": "MusicBrainz 发行组 ID",
  "fields.musicbrainz_disc_id": "MusicBrainz 碟片 ID",
  "fields.musicbrainz_release_status": "MusicBrainz 发行状态",
  "fields.musicbrainz_release_type": "MusicBrainz 发行类型",
  "fields.musicbrainz_release_country": "MusicBrainz 发行国家",
  "fields.musicip_id": "MusicIP ID",
  "fields.amazon_id": "Amazon ID",
} as const satisfies TranslationCatalog;
